### ISSUE TITLE
Sprint#14_Review วันที่ 1/11/2016

### ISSUE THREAD

**Issue by abyssEN** [mzget/rfl-sme-app#10]
**Full review document.**
https://1drv.ms/w/s!AuYLDM-kyd41qESHX6kq0Zhyy1jE

### webapp (business page) @abyssEN 

- [x] user status (offline, online)

- [x] fixed business logo to upload ratio

**Comment by mzget** [comment]
### User online status @me @atomxsk8
- [x] api for set status. @https://github.com/mzget/rfl-sme-app/wiki/User_api#online-status
- [x] set status when app pause.
- [x] set status when app resume.
- [x] set status when user logout.
