### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by mzget** [mzget/rfl-sme-app#3]
- swiper ไม่เลื่อน ตุ่ม
- check login facebook.
- [x] location permission.
- [x] picker หน้า personal info ไม่เซ็ตค่าเริ่มต้นให้ form 
- [x] picker หน้า official contact . 
- [x] picker สำหรับ set group ในหน้า links **ERROR**

**Comment by fiizxwinchester** [comment]
Meeting 18/10/2559
- [x] Popover
- [x] Picker
  - [x] ในหน้าที่มี Picker ในแอพแอนดรอยด์ เปลี่ยนจาก PickerAndroid เป็น Picker ธรรมดาแล้ว แต่ติด Bug ตรง     การ Submit ค่าของ Picker
  - [x]  Bug : OfficialContactView และ BussinessForm แก้ Bug พี่เก็ททำ @mzget 
  - [x]  SignUpView2 เปลี่ยนจาก PickerAndroid ให้เป็น Picker ธรรมดาแล้ว

หมายเหตุ
หน้าที่มี Picker : SignUpView2, OfficialContactView, SignUpBusinessForm, BusinesForm

**Comment by fiizxwinchester** [comment]
Task 21/10/2559
- [x]  หน้า Top 15 ทายาทที่แชร์จะต้องคลิกให้ได้
  - กับ Browser คลิกได้แล้วแต่กับ App ยังคลิกไม่ได้
- [x]  Preview Card แก้ Card ที่หายและไม่ให้ซูมได้
- [x]  แก้ CardCustomize ให้มีโลโก้อยู่ในการ์ด
- [x]  Bug : Avatar อัพโหลดภาพ ถ่ายภาพ พัง
- [x]  Claimed ทำให้กดปุ่มแล้วมีตัวเลือกในการเพิ่มภาพ 
- [x] แยก ImageCatalog.js เป็น Android และ iOS
- [x]  Bug : Claimed อัพโหลดภาพพัง

**Comment by fiizxwinchester** [comment]
Task 25/10/2559
- [x] ทำให้หน้า Explore สามารถแสดงค่า Distance ได้ด้วย

**Comment by fiizxwinchester** [comment]
Task วันอังคาร 25/10/2559
- [x] ทำหน้าท๊อป 15 ทายาท ใน App ให้คลิก Business ได้
- [x] Bug : Search หน้า Index พัง

**Comment by fiizxwinchester** [comment]
Task วันพุธ 26/10/2559
- [x] Google Map get Geo Location ในแอพไม่ทำงาน เกี่ยวกับการ get location ของ Device

**Comment by fiizxwinchester** [comment]
Task 7/11/2559
- [x] แก้เซฟการ์ดแล้วการ์ดไม่แสดง Android

**Comment by fiizxwinchester** [comment]
- [ ] [Bug] [Join Now – Customized Card] – ระบบไม่ได้ดึงเอาข้อมูลที่อยู่ตอนสมัครสมาชิกมาแสดงบน card ให้ (เลขที่บ้าน, หมู่ ถนน ซอย ….. ) ตอนนี้แสดงแค่ ตำบล อำเภอ จังหวัด ….

- [ ] [Bug] [Join Now – Customized Card] – เมื่อเปลี่ยน Card Style และ Layout บางครั้งพบว่า ข้อมูลที่แสดงใน Card แสดงไม่ครบ (ส่วนของ Contact หายไป)

- [ ] [Bug] [Join Now – Customized Card] – Font à Font Style เมื่อเปลี่ยน Font ที่ Preview ไม่เปลี่ยน

- [ ] [Bug] [Join Now – Customized Card] – ตอนกด Save Card ต้องกด 2 ครั้ง จึงจะไปหน้า Finish (ไม่แน่ใจว่าเพราะเครื่องที่ใช้ทดสอบ spec ต่ำ ทำให้ช้ารึเปล่า)

**Comment by fiizxwinchester** [comment]
Filter

- [ ] [Bug] [Return Result – Filter] – ข้อมูล Filter ยังไม่มี Look up (Status, Industry)

- [ ] [Bug] [Return Result – Filter] – ปุ่ม expand ของการ Filter : ถ้าย่ออยู่ ให้แสดงปุ่มลง V แต่ถ้าขยายอยู่ ให้แสดงปุ่มขึ้น ^

**Comment by fiizxwinchester** [comment]
BusinessCard

- [ ] กรณีที่ user ปลายทางยังไม่ได้ Links กับเจ้าของ card ส่วนของข้อมูลการติดต่อ (Contact) จะต้องซ่อนไว้อยู่

**Comment by fiizxwinchester** [comment]
- [ ] [Add] Content ที่อยู่ที่หน้า Homepage (Explore, News, How to, FAQ, Help) จะต้องแสดงการนับจำนวนการ share และ view และแสดงจำนวนนั้นที่แต่ละ content ด้วย (เหมือนที่แสดงที่หน้า How to แต่ที่หน้า How to ก็ไม่ถูก เพราะเป็นการแสดง View / Share ของ action ทืทำที่ Youtube ไม่ใช่การ share จาก App

**Comment by fiizxwinchester** [comment]
Task 10/111/2559
- [x] แก้ Picker หน้า Join now สมัครไม่ได้

**Comment by abyssEN** [comment]
- [x] recheck call function
- [x] recheck save to contact function
- [x] fix attach files (contact us)
- [x] login with facebook
### Chat
- [x] UI (type a message)
- [x] attach image
- [x] send location
- [x] location UI
### Link
- [x] recheck filter picker
- [x] set to Sub Claimer and Employee
- [x] set to optionsAll
- [x] fix myteam tab
- [x] display wrong number when change picker(card)
### nearby
- [x] send แล้วไม่หายไปจากรายการ **เนื่องจากandroid get locationไม่ได้ แก้ด้วยเอาenablehighaccuracyออก
### supportContact
- [x] upload images
- [x] take a photo

**Comment by abyssEN** [comment]
- [x] finish scene login button wrong UI
- [x] birthday picker
- [ ] notification
- [x] Link loading
- [x] Recheck QR **request camera permission**
- [x] webview background blur not show
- [x] background blur can scroll (overflow-y hidden)
- [x] Link load user fail
### avatar
- [x] Avatar not show (self)
