### ISSUE TITLE
web-smelink.net

### ISSUE THREAD

**Issue by mzget** [mzget/rfl-sme-app#8]
- [x] หน้า hightlight , Explore
- [x] หน้า news
- [x] หน้า howtos
- [x] เก็บ ข้อมูล recent search ถ้า user login 
- [x] หน้า explore กด item แล้วไม่ไป business page ต่อ

**Comment by fiizxwinchester** [comment]
Task 26/10/2559
- [x] หน้า Support ต้อง Design หน้าเว็บใหม่
- [x] หน้า Contacts Feedback Us ต้อง Design หน้าเว็บใหม่
- [x] หน้า Search ต้องทำให้กดดู business ได้ทั้งแถบ
- [x] Bug : ตรง Claimed ในหน้า Search สำหรับเว็บต้องกดแสดงหน้า Claim ที่ถูกต้อง

**Comment by fiizxwinchester** [comment]
Task 31/10/2559
- [x] อัปโหลดรูปหน้า Contact ทำ UI
- [x] Bug ; Claim Avatar เวลาเลื่อนขึ้นแล้วมันทับกับ nav bar

**Comment by fiizxwinchester** [comment]
Task 1/11/2559
- [x] แก้หน้า News
- [x] ดึงจำนวน Business จาก DB
- [x] ใส่ลูกศรในหน้า Support

**Comment by fiizxwinchester** [comment]
Task วันพุธ 2/11/2559
- [x] ตัดคำชื่อ Business
- [x] แก้ฟ้อนต์หน้า Discover
- [x] เพิ่ม Config ในเว็บ

**Comment by fiizxwinchester** [comment]
Task วันพฤหัส 3/11/2559
- [x] หน้า Responsive ในเว็บโชว์ nav bar ในแอพไม่ต้องแสดง

**Comment by fiizxwinchester** [comment]
Task วันศุกร์ 4/11/2559
- [x] Error Message : หน้า Index.html

**Comment by fiizxwinchester** [comment]
Task 10/11/2559
- [x] Bug: หน้า Search check status การ claimed 

*2 คือ pending ถ้ามันเป็น 1 ให้ขึ้น Claim by
- [x] CardView เมื่อ save card ตำแหน่ง avatar เพี้ยน
- [x] cardPreview ไม่มี Avatar ในการ์ด *\* หมายเหตุ Comment claimerBusiness.logo ไว้

**Comment by fiizxwinchester** [comment]
CustomizeCard
- [x] [Bug] [Join Now – Customized Card] – ระบบไม่ได้ดึงเอาข้อมูลที่อยู่ตอนสมัครสมาชิกมาแสดงบน card ให้ (เลขที่บ้าน, หมู่ ถนน ซอย ….. ) ตอนนี้แสดงแค่ ตำบล อำเภอ จังหวัด ….
- [ ] [Bug] [Join Now – Customized Card] – เมื่อเปลี่ยน Card Style และ Layout บางครั้งพบว่า ข้อมูลที่แสดงใน Card แสดงไม่ครบ (ส่วนของ Contact หายไป) **หมายเหตุ Style Narrow ข้อมูลมาครบแต่พื้นที่แสดงไม่พอ รอถามทางเค้าก่อน
- [x] [Bug] [Join Now – Customized Card] – Font à Font Style เมื่อเปลี่ยน Font ที่ Preview ไม่เปลี่ยน
- [x] [Bug] [Join Now – Customized Card] – ตอนกด Save Card ต้องกด 2 ครั้ง จึงจะไปหน้า Finish (ไม่แน่ใจว่าเพราะเครื่องที่ใช้ทดสอบ spec ต่ำ ทำให้ช้ารึเปล่า)

**Comment by fiizxwinchester** [comment]
Filter
- [x] [Bug] [Return Result – Filter] – ข้อมูล Filter ยังไม่มี Look up (Status, Industry)
- [x] [Bug] [Return Result – Filter] – ปุ่ม expand ของการ Filter : ถ้าย่ออยู่ ให้แสดงปุ่มลง V แต่ถ้าขยายอยู่ ให้แสดงปุ่มขึ้น ^

**Comment by fiizxwinchester** [comment]
BusinessCard
- [ ] กรณีที่ user ปลายทางยังไม่ได้ Links กับเจ้าของ card ส่วนของข้อมูลการติดต่อ (Contact) จะต้องซ่อนไว้อยู่ ***หมายเหตุ รอปรึกษาให้เค้าดีไซน์ การซ่อนแต่ละ Style มาให้

**Comment by fiizxwinchester** [comment]
task 11/11/2559
- [x] [Search – Suggest และ Return Result] – การแสดงรายละเอียดของบริษัท ใต้ชื่อบริษัท จะแสดงแค่ อำเภอ จังหวัด และ distance

**Comment by fiizxwinchester** [comment]
task 16/11/2559
- [x] ขาด icon แสดง Online Status (ถ้า online อยู่ แสดง icon สีเขียว / ถ้า offline จะแสดง icon สีเทา) ต้อง apply ทุกหน้าที่มีการแสดงวงกลมของ user) à Open
- [ ] Search_signup3.html แสดง geolocation

**Comment by fiizxwinchester** [comment]
Task 18/11/2559
- [ ] แก้ claimer avatar ที่ไม่ได้อัพโหลดรูปภาพ
- [ ] แก้ spinner
- [ ] แก้ Cardpreview กรณีที่ไม่ได้อัพโหลด avatar
- [ ] Production แก้คลิก Business
